# Generated by Django 3.2 on 2024-02-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20240214_0711"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="farm_image",
            field=models.TextField(
                blank=True, default="", help_text="나의 밭 이미지", null=True
            ),
        ),
    ]
