# Generated by Django 3.2 on 2024-02-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_farm_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="farm_image",
            field=models.TextField(
                blank=True,
                default="/media/farms/ab26494c84e8472f9390d7a46415b6de.png",
                help_text="나의 밭 이미지",
                null=True,
            ),
        ),
    ]
