# Generated by Django 3.2 on 2024-02-14 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dairyimage",
            name="diary",
            field=models.ForeignKey(
                help_text="일지",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="diary.diary",
            ),
        ),
        migrations.AlterField(
            model_name="dairyimage",
            name="path",
            field=models.TextField(help_text="저장 경로"),
        ),
        migrations.AlterField(
            model_name="diary",
            name="description",
            field=models.TextField(help_text="본문"),
        ),
        migrations.AlterField(
            model_name="diary",
            name="title",
            field=models.CharField(help_text="제목", max_length=100),
        ),
        migrations.AlterField(
            model_name="diary",
            name="type",
            field=models.CharField(
                choices=[("농업일지", "농업일지"), ("밭자랑", "밭자랑")],
                default="농업일지",
                help_text="일지 타입",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="diary",
            name="user",
            field=models.ForeignKey(
                help_text="작성자",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diaries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
