# Generated by Django 3.2 on 2024-02-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0003_auto_20240215_1417"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="farm_image",
            field=models.TextField(
                blank=True, default="", help_text="밭 자랑 이미지", null=True
            ),
        ),
    ]
