# Generated by Django 3.2 on 2024-02-14 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0002_auto_20240214_0840"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Farm",
        ),
    ]
