# Generated by Django 3.2 on 2024-02-14 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="main_image",
            field=models.TextField(
                blank=True, default="", help_text="대표 이미지", null=True
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="nickname",
            field=models.CharField(help_text="별명", max_length=50),
        ),
        migrations.AlterField(
            model_name="plant",
            name="plant_type",
            field=models.ForeignKey(
                blank=True,
                help_text="식물 종류",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plants",
                to="plant.planttype",
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="start_at",
            field=models.DateField(help_text="시작일"),
        ),
        migrations.AlterField(
            model_name="plant",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="유저",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="plantlog",
            name="complete_at",
            field=models.DateField(blank=True, help_text="완료기간", null=True),
        ),
        migrations.AlterField(
            model_name="plantlog",
            name="deadline",
            field=models.DateField(blank=True, help_text="마감일", null=True),
        ),
        migrations.AlterField(
            model_name="plantlog",
            name="is_complete",
            field=models.BooleanField(default=False, help_text="완료 여부"),
        ),
        migrations.AlterField(
            model_name="plantlog",
            name="plant",
            field=models.ForeignKey(
                help_text="식물",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="plant.plant",
            ),
        ),
        migrations.AlterField(
            model_name="plantlog",
            name="type",
            field=models.CharField(
                choices=[("물주기", "물주기"), ("시작", "시작"), ("분갈이", "분갈이")],
                default="물주기",
                help_text="로그 타입",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="planttype",
            name="main_image",
            field=models.TextField(
                blank=True, default="", help_text="대표 이미지", null=True
            ),
        ),
        migrations.AlterField(
            model_name="planttype",
            name="name",
            field=models.CharField(help_text="이름", max_length=50),
        ),
        migrations.AlterField(
            model_name="planttype",
            name="repotting_cycle",
            field=models.PositiveIntegerField(help_text="분갈이 주기"),
        ),
        migrations.AlterField(
            model_name="planttype",
            name="watering_cycle",
            field=models.PositiveIntegerField(help_text="물주기 주기"),
        ),
    ]
