# Generated by Django 3.2 on 2024-02-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant", "0002_auto_20240214_0840"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantlog",
            name="complete_at",
            field=models.DateField(blank=True, help_text="완료일", null=True),
        ),
    ]
