# Generated by Django 3.2 on 2024-02-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant", "0003_alter_plantlog_complete_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="planttype",
            name="blooming_season",
            field=models.CharField(
                blank=True, default="", help_text="개화 시기", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="planttype",
            name="features",
            field=models.CharField(
                blank=True, default="", help_text="작물 특성", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="planttype",
            name="humidity",
            field=models.CharField(
                blank=True, default="", help_text="습도", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="planttype",
            name="introduction",
            field=models.TextField(
                blank=True, default="", help_text="작물 소개", null=True
            ),
        ),
        migrations.AddField(
            model_name="planttype",
            name="sunlight",
            field=models.CharField(
                blank=True, default="", help_text="햇빛", max_length=300, null=True
            ),
        ),
        migrations.AddField(
            model_name="planttype",
            name="temperature",
            field=models.CharField(
                blank=True, default="", help_text="온도", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="planttype",
            name="watering_method",
            field=models.CharField(
                blank=True, default="", help_text="물 주기 방법", max_length=300, null=True
            ),
        ),
        migrations.AlterField(
            model_name="planttype",
            name="repotting_cycle",
            field=models.PositiveIntegerField(
                blank=True, default="", help_text="분갈이 주기", null=True
            ),
        ),
        migrations.AlterField(
            model_name="planttype",
            name="watering_cycle",
            field=models.PositiveIntegerField(
                blank=True, default="", help_text="물주기 주기", null=True
            ),
        ),
    ]
